exp_name: "my_PPO_LanguageGridWorld_10x10_1"
model_name: "my_PPO_LanguageGridWorld_10x10_simple_bert"
type: "language"
embedding_size: "simple_bert"
share: false
seed: 40
cuda: true
total_timestamp: 1000000
learning_rate: 0.00025
num_steps: 64
n_envs: 32
num_minibatches: 32
gamma: 0.99
gae_lambda: 0.95
clip_eps: 0.2
n_epochs: 4
ent_coeff: 0.0
vf_coeff: 0.5
anneal_lr: false
policy: "MultiInputPolicy"